
services:
  database:
    image: mariadb:10.3.30
    environment:
      MARIADB_DATABASE: 'app'
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: 'password'
      MARIADB_ROOT_PASSWORD: 'rootpass'
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'no'
    ports:
      - '3309:3306'

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8009:80'
    environment:
      PMA_HOST: database
    depends_on:
      - database
